import type { Book, SliderItem, Partner, Order } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "رياضيات الجبر الأساسية",
    author: "أحمد السعدي",
    category: "cours",
    level: "college",
    language: "ar",
    price: 18.99,
    image: "/algebra-textbook-arabic.jpg",
    images: ["/algebra-textbook-arabic.jpg", "/algebra-textbook-arabic.jpg", "/algebra-textbook-arabic.jpg"],
    description: "كتاب شامل في الجبر الأساسي للمرحلة الابتدائية",
    rating: 4.5,
    reviews: 124,
    status: "En stock",
  },
  {
    id: "2",
    title: "Histoire de la Tunisie",
    author: "Fatima Meziane",
    category: "histoire",
    level: "lycee",
    language: "fr",
    price: 22.99,
    image: "/history-textbook-tunisia.jpg",
    images: ["/history-textbook-tunisia.jpg", "/history-textbook-tunisia.jpg", "/history-textbook-tunisia.jpg"],
    description: "Un livre complet sur l'histoire de la Tunisie pour les étudiants du secondaire",
    rating: 4.8,
    reviews: 89,
    status: "En stock",
  },
  {
    id: "3",
    title: "Physics Fundamentals",
    author: "Dr. Ahmed Khalil",
    category: "cours",
    level: "lycee",
    language: "en",
    price: 25.99,
    image: "/physics-textbook-fundamentals.jpg",
    images: ["/physics-textbook-fundamentals.jpg", "/physics-textbook-fundamentals.jpg", "/physics-textbook-fundamentals.jpg"],
    description: "Comprehensive physics textbook for secondary students",
    rating: 4.6,
    reviews: 156,
    status: "En stock",
  },
  {
    id: "4",
    title: "البرمجة بلغة بايثون",
    author: "محمد علي",
    category: "writing",
    level: "preparatoire",
    language: "ar",
    price: 35.99,
    image: "/python-programming-arabic.jpg",
    images: ["/python-programming-arabic.jpg", "/python-programming-arabic.jpg", "/python-programming-arabic.jpg"],
    description: "مرجع شامل لتعلم البرمجة باستخدام لغة بايثون",
    rating: 4.7,
    reviews: 203,
    status: "En stock",
  },
  {
    id: "5",
    title: "Littérature Française Classique",
    author: "Marie Leclerc",
    category: "devoirs",
    level: "lycee",
    language: "fr",
    price: 19.99,
    image: "/french-literature-classic.jpg",
    images: ["/french-literature-classic.jpg", "/french-literature-classic.jpg", "/french-literature-classic.jpg"],
    description: "Études des grands auteurs de la littérature française",
    rating: 4.4,
    reviews: 78,
    status: "En stock",
  },
  {
    id: "6",
    title: "Introduction to Calculus",
    author: "Prof. Hassan Nour",
    category: "cours",
    level: "preparatoire",
    language: "en",
    price: 39.99,
    image: "/calculus-university-textbook.jpg",
    images: ["/calculus-university-textbook.jpg", "/calculus-university-textbook.jpg", "/calculus-university-textbook.jpg"],
    description: "Essential calculus concepts for university students",
    rating: 4.9,
    reviews: 312,
    status: "En stock",
  },
]

export const mockSliders: SliderItem[] = [
  {
    id: "1",
    title: " ",
    subtitle: " ",
    image: "/DEMO-BANNER.png",
    cta: " ",
    link: " ",
  },
  {
    id: "1",
    title: " ",
    subtitle: " ",
    image: "/demo-banner2.png",
    cta: " ",
    link: " ",
  }
]

export const mockPartners: Partner[] = [
  {
    id: "1",
    name: "Ali Mansouri",
    email: "ali@example.com",
    phone: "+216 92 345 678",
    bookTitle: "الرياضيات المتقدمة",
    category: "cours",
    level: "lycee",
    language: "ar",
    description: "كتاب شامل في الرياضيات للمرحلة الثانوية",
    createdAt: new Date("2024-01-15"),
  },
]

export const mockOrders: Order[] = [
  {
    id: "1",
    bookId: "1",
    quantity: 2,
    totalPrice: 37.98,
    customerName: "Amina Jouini",
    customerEmail: "amina@example.com",
    createdAt: new Date("2024-01-10"),
  },
]
